### ISSUE TITLE
Doesn't Work On Mac

### ISSUE THREAD

**Issue by ghost** [destruc7i0n/SublimeMinecraftCommandFormat#2]
I remember you telling me how to do it, but I simply don't understand and I don't have the files.
Also it would be easier to use on a web page

**Comment by destruc7i0n** [comment]
Here is a tutorial made on a Mac that may help/guide you through the whole process :rocket: 

https://www.youtube.com/watch?v=oV0P_Y1SWuQ

**Comment by ghost** [comment]
that is outdated, the page has changed

**Comment by destruc7i0n** [comment]
Maybe this updated one? https://www.youtube.com/watch?v=ioRbV7fQkdU (For Windows, but I think the guy talks about MAC too.

**Comment by ghost** [comment]
He has package control already installed, i don't know how to get it (i use yosemede)

**Comment by destruc7i0n** [comment]
Maybe this? https://www.youtube.com/watch?v=KAWQc7ZK05U

**Comment by destruc7i0n** [comment]
Just go up to the installation of Package Control

**Comment by ghost** [comment]
never mind i found the sublime text 2 download
